[workspace]
exclude = []
members = [
  "packages/asset",
  "packages/protocol",
]

[profile.release]
codegen-units = 1
debug = false
debug-assertions = false
lto = true
opt-level = "z"
overflow-checks = true
rpath = false
