[package]
authors = ["Apollo Dev"]
edition = "2018"
name = "apollo-protocol"
version = "0.13.0"

[dependencies]
apollo-asset = {path = "../asset"}
cosmwasm-std = {version = "1.0.0", features = ["iterator"]}
#cw-asset = {rev = "fafac0755d040764c15417812280ce022dc05aea", git = "https://github.com/apollodao/cw-asset.git"}
cw-asset = {tag = "v2.2.0", git = "https://github.com/mars-protocol/cw-asset.git"}
cw-storage-plus = "0.14.0"
cw20 = {version = "0.14.0"}
cw20-base = {version = "0.14.0", features = ["library"]}
schemars = "0.8.10"
serde = {version = "1.0.144", default-features = false, features = ["derive"]}
thiserror = {version = "1.0.32"}
# Remove this
cosmwasm-storage = "1.0.0"

[dev-dependencies]
cosmwasm-schema = {version = "1.0.0"}
cw-multi-test = {version = "0.14.0"}
cw-utils = {version = "0.14.0"}
test-case = {version = "2.2.1"}
