[package]
authors = ["Apollo Dev"]
edition = "2018"
name = "apollo-protocol"
version = "0.13.0"

[dependencies]
apollo-asset = {path = "../asset"}
cosmwasm-std = {version = "1.1.0", features = ["iterator"]}
cw-asset = "2.4.0"
cw-storage-plus = "0.16.0"
cw20 = {version = "0.16.0"}
cw20-base = {version = "0.16.0", features = ["library"]}
schemars = "0.8.11"
serde = {version = "1.0.147", default-features = false, features = ["derive"]}
thiserror = {version = "1.0.37"}
# Remove this
cosmwasm-storage = "1.1.0"
cosmwasm-schema = {version = "1.1.0"}

[dev-dependencies]
cw-multi-test = {version = "0.16.0"}
cw-utils = {version = "0.16.0"}
test-case = {version = "2.2.2"}
