[package]
authors = ["Apollo Dev"]
edition = "2018"
name = "apollo-asset"
version = "0.11.0"

[dependencies]
apollo-proto-rust = {branch = "master", git = "https://github.com/apollodao/apollo-proto-rust.git"}
cosmwasm-std = {version = "1.0.0", features = ["iterator"]}
cw-storage-plus = {version = "0.13.4"}
cw20 = {version = "0.13.4"}
schemars = "0.8.1"
serde = {version = "1.0.103", default-features = false, features = ["derive"]}
thiserror = {version = "1.0.24"}

[dev-dependencies]
cosmwasm-schema = {version = "1.0.0"}
cw-multi-test = {version = "0.13.4"}
cw-utils = {version = "0.13.4"}
test-case = {version = "2.1.0"}
