[package]
authors = ["Apollo Dev"]
edition = "2018"
name = "apollo-asset"
version = "0.11.1"

[dependencies]
apollo-proto-rust = {branch = "master", git = "https://github.com/apollodao/apollo-proto-rust.git"}
cosmwasm-std = {version = "1.0.0", features = ["iterator"]}
cw-storage-plus = {version = "0.14.0"}
cw20 = {version = "0.14.0"}
schemars = "0.8.10"
serde = {version = "1.0.144", default-features = false, features = ["derive"]}
thiserror = {version = "1.0.32"}

[dev-dependencies]
cosmwasm-schema = {version = "1.0.0"}
cw-multi-test = {version = "0.14.0"}
cw-utils = {version = "0.14.0"}
test-case = {version = "2.2.1"}
