[package]
authors = ["Apollo Dev"]
edition = "2018"
name = "apollo-asset"
version = "0.13.0"

[dependencies]
apollo-proto-rust = {branch = "master", git = "https://github.com/apollodao/apollo-proto-rust.git"}
cosmwasm-std = {version = "1.1.0", features = ["iterator"]}
cw-storage-plus = {version = "0.16.0"}
cw20 = {version = "0.16.0"}
schemars = "0.8.10"
serde = {version = "1.0.147", default-features = false, features = ["derive"]}
thiserror = {version = "1.0.37"}
cosmwasm-schema = {version = "1.1.0"}

[dev-dependencies]
cw-multi-test = {version = "0.16.0"}
cw-utils = {version = "0.16.0"}
test-case = {version = "2.2.2"}
