[package]
name = "apollo-asset"
version = "1.0.0"
authors = ["Apollo Dev"]
edition = "2018"

[dependencies]
cosmwasm-std = { version = "1.0.0", features = ["iterator"] }
schemars = "0.8.1"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
cw20 = { version = "0.13.4" }
cw-storage-plus = { version = "0.13.4" }
thiserror = { version = "1.0.24" }

[dev-dependencies]
cosmwasm-schema = { version = "1.0.0" }
cw-multi-test = { version = "0.13.4" }
cw-utils = { version = "0.13.4" }
test-case = { version = "2.1.0" }
