name: Security audit
on:
  push:
    paths: 
      - '**/Cargo.toml'
      - '**/Cargo.lock'
  schedule:
    - cron: '0 0 * * *'
env:
  CARGO_TERM_COLOR: always
  GIT_CREDENTIALS: https://apollodao-ci:${{ secrets.APOLLO_CI_PAT }}@github.com/
jobs:
  security_audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.APOLLO_CI_PAT }}